# Generated by Django 3.0.2 on 2020-01-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='present_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='present',
            unique_together={('officer', 'present_date')},
        ),
    ]
